### ISSUE TITLE
Your extension makes Vscode Extension : Html language features error.

### ISSUE THREAD

**Issue by Salehdabab** [panoply/vscode-liquid#28]
Hi, 

So i tried enabling extensions 1 by 1 on any project i work on, as soon as your extension is enabled, and i try to edit my files, the extension from VScode itself, called HTML language features, constantly error from it. 

See below for the error,  i tried reinstalling and reloading VS, and the error still occurs on everything i try and edit, this happens in all projects i try,(tried over 15 different). 

As soon as i disable your extension, everything works fine. 

Could you please look into this? 

`[Error - 10.14.51] Error while validating file:///c%3A/Dev/shopify-theme/snippets/back-to-the-top.liquid: Cannot read property 'validProperties' of null
TypeError: Cannot read property 'validProperties' of null
    at e.getSetting (c:\Users\Saleh Dababneh\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:1:918556)
    at new e (c:\Users\Saleh Dababneh\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:1:921864)
    at Function.e.entries (c:\Users\Saleh Dababneh\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:1:922067)
    at e.doValidation (c:\Users\Saleh Dababneh\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:1:931609)
    at Object.doValidation (c:\Users\Saleh Dababneh\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:1:451816)
    at o.version.i.forEach.e (c:\Users\Saleh Dababneh\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:1:410747)
    at Array.forEach (<anonymous>)
    at c:\Users\Saleh Dababneh\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:1:410560
`

**Comment by panoply** [comment]
@Salehdabab update to v2.2.2 and this should fix the error, let me know.

**Comment by Salehdabab** [comment]
Same error, different project, after updating to v2.2.2

`[Error - 11.18.36] Error while validating file:///c%3A/Dev/shopify-theme/snippets/newsletter.liquid: Cannot read property 'validProperties' of null
TypeError: Cannot read property 'validProperties' of null
    at e.getSetting (c:\Users\Saleh Dababneh\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:1:918556)
    at new e (c:\Users\Saleh Dababneh\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:1:921864)
    at Function.e.entries (c:\Users\Saleh Dababneh\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:1:922067)
    at e.doValidation (c:\Users\Saleh Dababneh\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:1:931609)
    at Object.doValidation (c:\Users\Saleh Dababneh\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:1:451816)
    at o.version.i.forEach.e (c:\Users\Saleh Dababneh\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:1:410747)
    at Array.forEach (<anonymous>)
    at c:\Users\Saleh Dababneh\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\htmlServerMain.js:1:410560
`

**Comment by panoply** [comment]
What other extensions do you have running? It's just your log should indicate it's this extension causing the error. Did you restart after updating?

**Comment by Salehdabab** [comment]
I have disabled all other extensions and only have yours on at the moment, as i turn yours on, and try to edit something constant errors are given

**Comment by Salehdabab** [comment]
And i did restart the program after update and multiple times before

**Comment by panoply** [comment]
I am unable to recreate this issue in my environment. When did this issue start to occur? Can you end my your settings preferences?

**Comment by Salehdabab** [comment]
It has been going for a couple weeks, had disabled the html extension from vscode to avoid it, didn't think it was due to some of the extensions i had installed. Which settings file would you need

**Comment by panoply** [comment]
Your workspace settings. Also update to v2.2.3 and tell if it still occurs

**Comment by Salehdabab** [comment]
Updated to 2.2.3 and still errors, my settings.json is empty, didnt make any changes, (haven't used VScode editor that much) So if you could guide me to it, would be great.

**Comment by panoply** [comment]
Read the vscode  [documentation](https://code.visualstudio.com/docs/getstarted/settings)

**Comment by Salehdabab** [comment]
The workplace settings file is empty, since i made no changes, I read the documentation, nothing i can show you here, just using VScode out of the box. Default settings is shown here https://code.visualstudio.com/docs/getstarted/settings#_default-settings

**Comment by panoply** [comment]
Closing this due to insufficient information, an inability to recreate the issue my end and the lack of understanding from the author.
